apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wanderblog-eks-cluster
  region: us-east-1
  version: "1.36" 
  tags:
    owner: thanuesh-shell
    bu: cwg
    project: wanderblog

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  withOIDC: true

managedNodeGroups:
  - name: wanderblog-node-group
    instanceType: m7i-flex.large
    minSize: 2
    maxSize: 2
    privateNetworking: true
    volumeSize: 20
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: false
        certManager: yes
        ebs: true
        fsx: false
        efs: false
        albIngress: true
        xRay: false
        cloudWatch: false
    labels:
      lifecycle: ec2-autoscaler
