---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgDD77I1fUu9t8+8gBLte4rQSH48ZsLfs4NUBppN72418SJI7/9G0YoxTZdl/WPBFVctiQR52KPl79bKhJjsLC4qt6xSOzDCDZr/JmId/TZ/9r2+ENUrlCCDa+tfWt6M7Zaz+wcEotEQkXk8x+JVPzu0LCuNBBK5HpEHsIx+qL5Ykx78Nr0eq/vgSpgqnvNi8sCzDIh6bCJhLHr/oWEnnj1ABGm5SwMRjkM6ujgRJ0dQ+V8ImCRaqfh/PK8R45X+ZTkyGa/eUyWWjZN22VcHhER7x9deljV1+NG6vIkPXyONDjj3Uumh4U2Wmr9tw1quDvo6WN/oxpNcF5Okw46ef7Z4FveRJiNqKMV4C2iYr7heVSCXc4w11HKN1yrTuMDkuh17LX8bZZwHyQiNDaxQZfgkFaGEfai8LaRqSzgWBRlAQDybeS1xkzPvTTIrCUtF7vJPftacMocXtsgHivniDWCRnlSoUcpHgyYVf7L9Y0nePtGh7/onlavTgf0bVciRwX8Oo0K9xMJlX6CSAXtKvTESpF8JGxYNAyKnA+21gz0ifhcquMIVSc6tsr9pKzYT1s3FxQztl4R29yuk9YMUYNzuORql+eLEMfVWbeILlxVmkAiohkIm4pELqj56QEGnSuf0JS6IERfXUhxkvd2PWsPCc+WFcCU5/aL7r9g1oIJn1nsSl0W7oz7CHUImVzpAR3snKyqnnI6OT1ucrgewtqyd9iekmgoF9h43bfZu/3XJIG6pfwGLl8HriBIfhF3d5/nFJGjJXIe6vm3Q1NSaYVRWuXS9dw==
  template:
    metadata:
      name: backend-secrets
      namespace: default
