---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgCJrYmbgUBdAdA4P+h7mpeHjvdQNZkkpgiOOPfWiP7/BrenFZWtoZ+wjU9TvM199vy3azwzgaqJeFrtzVAYX96V+l7c2UBfSVlRxmEl3R7wy9mE3oGJ+2Drh0FO/M1uj27rWqkmUwpRK+7Cw+5HuTjl118W7xN9+XAnoMT3T6lulV0EInwvKS4UZbnyuBCbdSaJDc/WRS8KtUsJv6fMLrpr76EUO7VQ/iJyx8VLPT0sFkb7GZKA64IjUydCEk6PUkFmmTfk3J/t+k0iVPH3GS1vwuhY8BS42GxvMCGsOG94nfQD5JlEgY98y6s2hBTZdOig97HN8uD7VkhEF3rdvc215T6YjD862P7O1YyawocteNPQkPvVrKW9ZV4CcbaNqJf0/V8vFARJGVZ+6goS5mI5ho3THAGS91F6M0uKAoAKjy3wDsHYS/8BCACV1RkkLDXqab8z7Uxkem54Be7eXGPMIvZ4SkhYzed1EWKyTJTvBb7WQ6EH8powFO4HqkczkantQKml9SlHcdN+2ylTmj7o2n2d2TVhHJVEorDEArXb2/T8be3I+SRI2UhEbCcTLrLmzuzCuZXgyYnnT1GfYyqT0jh43jvBAfZFNDM+D8S9X7nc5gdYaaOJxp1U1TksBpr2+Q49C6ILvj0FG3Y4lNwdpKprwEDR8zDB5wQ5TfAogPCYO6doVUskK7db6M3IwL2GUNoqG60/x+rZxcaTfYjzhHvNXlAtpnbYjK5DIHv6r3alBZMKY9R92K2QRI7l0RFSGsYk8cqiIuxoedeMKTZm85St9Q==
  template:
    metadata:
      name: backend-secrets
      namespace: default
