---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAPajmKwHaazmgGkobPC5iCh7dDUwe9AnZMHCp7wnDEBMtlmUs6jK8sqtPkK49I1M8fIwpfd/xPtvUhKCKB3pxjF1tLEekdPIJ8+1fgczsmlalAHBbED6Uxg8v8xA0G9QyviwhzBEMO4zoiRvKg8fj+fARIJwUBBbI7gptqCdtFeJXxA7XpQ2pcEoSq5xzVUa3Xapz6wbgIlxvGPijKT0OjyVB1nDF7x9K4/aVLrJzX2Dpt4d4F2Au8hJk3+3osG3MxRCL/3x9tpE4aAozZYr79VGvL00v+Vc3t5cNp33/Rcr2dwygZMdlW5IGZQxsTeCcK5M+2F6X/nBglSUMeX8quhjsjv9dWBnJNwWaJn7sHrgcb7/ZvGkKOGJQixalQVWqvxjMiQlHwdwhDtTS2SR26wgfs4PJnOphXFrcNrVx3yJuI41BwrrrWgSoSNc1PSw5wbok1By+95awchGdvcik0ka4DQsAUsrYc/rf7bIbMNhqPa5/U7gmKkK1ke4g+yiDPMCxbxhP9Mm3PMM87ZgyZs9xVQo/W5KIE49N/Z5qGuS2tw3Qk4zeQxj/MLG+B8WyXdbRxTruCXw9xNiaAJJ0q1XwZxNx+ITRQySqvZN5WO4RLTagMfyM/wUAnAaiVM/bTE3ARYhI2oiu/KuOhKqsDnB4/vJkuUBfL4/+kE1b1EVgTyGCkq/jYiseRm2G3H+Xt+LdfSuXNU+MD
    MONGO_INITDB_ROOT_USERNAME: AgC4fT1TRf/8PQwfXju5iqXc/shu5y7NyA3WyT/71ae9KgNzjafsdXon7Q5qqzpBue0LSN2xVzOWggp/pZs//4zf/byDBWvs5IpVgPd+rWxHrIsbhIsU6smScoRS//04EVAKUdQuHAckC3rTFEYSzLaa42dd9krzdYiP2S6XvsmrhltDc/tnzibO0YCAWBE6jdGwwqDLR4LiL/9hDrxYzUc7IFIC8T84CKsbLxh/aaqr7WZegkNP4s4fqvbXEE7H/aK9nTM7MDKWjRsbTIHoqBQ6L4fGBtPMtcJqyfDerNd8XxyAy//7CUBhd/Z+ktOtA27Edowv6AE8kXOu9zzS4z7J2X6EuSwtQNy/Ds8coNwsFpV0CZ+CaHvVmeMrrKy608aFuDlKqvlOzc15Mkm+xOXX5q42JQSIt6bv7f+vXM/mS0EGFcjHJDBt+c1EgljzwZ0rsOO28kiTM2KHl7CBH0aZq/PSVMieI1iAFtKIwdhy3U5bs9eFOB3ppT9XA0te1XYNtBGoB0QTxsn1anQWNuihEFL4xwNR+4Mye5Qi2b9dWUoeZnzt9HC3ZIokmjhzDpVQtRSehdPFM9beU4oY43kaPCITLl7obwdbCeHrY0mt6pZtXwB406rUAUcz0tt1xBocFrf12I1DgkInorkHl87+1XsPiK3kp/yOoZJTluo/XFCprs3Dw0ll2Umn5uYBKFz3uoy0+A==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
