---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAfUOH1PUzD7FwGGLWH1hcMxTyKHKN+6F7R4b5+fAU2lcNzf+tO63uxVi20weFXFarcf1NxWxxOCyQhlvPlEnDPAmptJXZE3gcoUVqOd57YUIPjjil+NWCsfyB5VfMJL6e+5SI2DVb9OFU5Sgneo842ayfO11CL3KXtwbdo/2j1YSXJ0K4G53iFvwNzUoh9/Ps7b+aWIh2himJie0gzizdEVVQOH1NYNHxHvmoy97eCRcI7NOYb8X2u5abx1urCzEdH9cIfXWVTGhX0VnKJhomwMWXDScTLO9iKl3hsBGuY/uCkeXiLY080bFrx3TrdfWMUtIWZ4lL8WwC5lGIO8M/uXRnSj79Mc5xkrXxJpM8VEIzgox/qcrCt2yYFc1a3ASA4FeIQzt9ucuuFeFO6u7kMGwmC8GfyvgjwzFzHG7s8/xbtNXFeFZDv9bUDLXXVbmJCdS55EbcdOy3sRVbqWWPLlbjJcnxS/wnDKDbQbIUAoP1IGhedIX9Du+Bwx8eRyjODQyta1iezsjU0u0wXv0u23DztL/fdIqmDWN/WZRZbCgn5hgRDmi/IoaeTBipTcH35AJcudbPnLWH6stQPPRiKFuHPkwFYf8XCeHYa5LploGaMtLIUVB2of8UELhaRjUdgJWU89AZnDKSJGB9XV1TqDEkDJS2fVBr7oGcWpEvUYKCuNhGEjb6UUpcZqa1DxG+2P1E353p8oTbE
    MONGO_INITDB_ROOT_USERNAME: AgAwj5Mh6qblGnpfDAJCxVENc+0AqMVJpYWvVAaA0/RHaTWnE3kTtR+OxbwnLFOejySoBEl8+OStgROye/MNlLRd/i4NdV1pl6p7XybHy4wG6LonTe5kpvM9o5ILGvTLw9K2C5QNR6SQMdqpQBEdBDFzWxc8ypXM73lA3TiKZQSInFr0R2tGTN2ttTPw0CCYgkGHfWpCoPdJC6ojJJ4KZSX036xNAq9Jvyout6hne8DQZJDYaUvO+ih95j+3jekQevypHJ27UqX8B5U6tWD4vQjFYch/fEEqhZdXEYlG6Z6C0Rg7YPhF8Mitj/5Hh/ISSsBEl7JiIWuJEFXIAh4q9FVUYYDJ+IOUem4Hq15KUer0hJMTCmHj8mzglCFdNaeuDnchY3Vl9HLyjghzp8dfH/QrUoqRlz37l15LRUC+QCr5jxKOMTcoafSyeT4Whi+N8dGCqIx+8YMmfK6jqTh7UPtzcSWTP7OcwrKMdY7XDIy7idOFi3JYTUeASaPc2qiwV6W6+UgSjz8wv+ivURpoJlddfiIdxZuAV8xubHwcMYewpM4kwTLS5FtHtjFvjcpeO3FHuN7u4Y1tlNJDBdirkMX0vJI+WX8xfOcoA7Px/trTMQvC3WMoUipPxqZ2hf4j3zMUQWvAs2NODmOXubmVGRHmPbMtMfI2N2OzV91T+bMRTpfl7Pg5GIZIYmrMqRymjnBiuJxI0Q==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
